spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: telegram-bot-database
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: telegram-bot-database-secret
                   key: user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: telegram-bot-database-secret
                   key: password
            - name: TELEGRAM_TOKEN
              value: 829504574:AAEjoaDiD0118_YFI88g94CI5eIfo7wCnpY
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
